

swipe:
  3: 
    left: 
      command: 'ydotool key super+shift+h'
    right: 
      command: 'ydotool key super+shift+l'
    up: 
      command: 'ydotool key super+d'
    down: 
      command: 'ydotool key super'
  4:
    left: 
      command: 'ydotool key super+l'
    right: 
      command: 'ydotool key super+h'
    up: 
      command: 'ydotool key super+j'
    down: 
      command: 'ydotool key super+k'
pinch:
  in:
    command: 'ydotool keydown ctrl click 4 keyup ctrl'
  out:
    command: 'ydotool keydown ctrl click 5 keyup ctrl'



# swipe:
# 3:
# left:
# command: exec i3 focus right
# right:
# command: exec i3 focus left
# up:
# command: exec i3 focus down
# down:
# command: exec i3 focus up
# 4:
# left:
# command: exec i3 workspace next
# right:
# command: exec i3 workspace prev
# up:
# command: exec i3 fullscreen toggle
# down:
# command: exec i3 floating toggle
# pinch:
# in:
# command: 'xdotool key ctrl+plus'
# out:
# command: 'xdotool key ctrl+minus'




# threshold:
# swipe: 0.4
# pinch: 0.4

# interval:
# swipe: 0.8
# pinch: 0.1
